// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.co.mdc.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import uk.co.mdc.model.ConceptualDomain;
import uk.co.mdc.model.ConceptualDomainDataOnDemand;
import uk.co.mdc.model.ConceptualDomainIntegrationTest;

privileged aspect ConceptualDomainIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConceptualDomainIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConceptualDomainIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConceptualDomainIntegrationTest: @Transactional;
    
    @Autowired
    private ConceptualDomainDataOnDemand ConceptualDomainIntegrationTest.dod;
    
    @Test
    public void ConceptualDomainIntegrationTest.testCountConceptualDomains() {
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to initialize correctly", dod.getRandomConceptualDomain());
        long count = ConceptualDomain.countConceptualDomains();
        Assert.assertTrue("Counter for 'ConceptualDomain' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConceptualDomainIntegrationTest.testFindConceptualDomain() {
        ConceptualDomain obj = dod.getRandomConceptualDomain();
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to provide an identifier", id);
        obj = ConceptualDomain.findConceptualDomain(id);
        Assert.assertNotNull("Find method for 'ConceptualDomain' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ConceptualDomain' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConceptualDomainIntegrationTest.testFindAllConceptualDomains() {
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to initialize correctly", dod.getRandomConceptualDomain());
        long count = ConceptualDomain.countConceptualDomains();
        Assert.assertTrue("Too expensive to perform a find all test for 'ConceptualDomain', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ConceptualDomain> result = ConceptualDomain.findAllConceptualDomains();
        Assert.assertNotNull("Find all method for 'ConceptualDomain' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ConceptualDomain' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConceptualDomainIntegrationTest.testFindConceptualDomainEntries() {
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to initialize correctly", dod.getRandomConceptualDomain());
        long count = ConceptualDomain.countConceptualDomains();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ConceptualDomain> result = ConceptualDomain.findConceptualDomainEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ConceptualDomain' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ConceptualDomain' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConceptualDomainIntegrationTest.testFlush() {
        ConceptualDomain obj = dod.getRandomConceptualDomain();
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to provide an identifier", id);
        obj = ConceptualDomain.findConceptualDomain(id);
        Assert.assertNotNull("Find method for 'ConceptualDomain' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConceptualDomain(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ConceptualDomain' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConceptualDomainIntegrationTest.testMergeUpdate() {
        ConceptualDomain obj = dod.getRandomConceptualDomain();
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to provide an identifier", id);
        obj = ConceptualDomain.findConceptualDomain(id);
        boolean modified =  dod.modifyConceptualDomain(obj);
        Integer currentVersion = obj.getVersion();
        ConceptualDomain merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ConceptualDomain' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConceptualDomainIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to initialize correctly", dod.getRandomConceptualDomain());
        ConceptualDomain obj = dod.getNewTransientConceptualDomain(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ConceptualDomain' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ConceptualDomain' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConceptualDomainIntegrationTest.testRemove() {
        ConceptualDomain obj = dod.getRandomConceptualDomain();
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConceptualDomain' failed to provide an identifier", id);
        obj = ConceptualDomain.findConceptualDomain(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ConceptualDomain' with identifier '" + id + "'", ConceptualDomain.findConceptualDomain(id));
    }
    
}
