// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.co.mdc.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import uk.co.mdc.model.Dataelement;
import uk.co.mdc.model.DataelementDataOnDemand;
import uk.co.mdc.model.DataelementIntegrationTest;

privileged aspect DataelementIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DataelementIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DataelementIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DataelementIntegrationTest: @Transactional;
    
    @Autowired
    private DataelementDataOnDemand DataelementIntegrationTest.dod;
    
    @Test
    public void DataelementIntegrationTest.testCountDataelements() {
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to initialize correctly", dod.getRandomDataelement());
        long count = Dataelement.countDataelements();
        Assert.assertTrue("Counter for 'Dataelement' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DataelementIntegrationTest.testFindDataelement() {
        Dataelement obj = dod.getRandomDataelement();
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to provide an identifier", id);
        obj = Dataelement.findDataelement(id);
        Assert.assertNotNull("Find method for 'Dataelement' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Dataelement' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DataelementIntegrationTest.testFindAllDataelements() {
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to initialize correctly", dod.getRandomDataelement());
        long count = Dataelement.countDataelements();
        Assert.assertTrue("Too expensive to perform a find all test for 'Dataelement', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Dataelement> result = Dataelement.findAllDataelements();
        Assert.assertNotNull("Find all method for 'Dataelement' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Dataelement' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DataelementIntegrationTest.testFindDataelementEntries() {
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to initialize correctly", dod.getRandomDataelement());
        long count = Dataelement.countDataelements();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Dataelement> result = Dataelement.findDataelementEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Dataelement' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Dataelement' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DataelementIntegrationTest.testFlush() {
        Dataelement obj = dod.getRandomDataelement();
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to provide an identifier", id);
        obj = Dataelement.findDataelement(id);
        Assert.assertNotNull("Find method for 'Dataelement' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDataelement(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Dataelement' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataelementIntegrationTest.testMergeUpdate() {
        Dataelement obj = dod.getRandomDataelement();
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to provide an identifier", id);
        obj = Dataelement.findDataelement(id);
        boolean modified =  dod.modifyDataelement(obj);
        Integer currentVersion = obj.getVersion();
        Dataelement merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Dataelement' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataelementIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to initialize correctly", dod.getRandomDataelement());
        Dataelement obj = dod.getNewTransientDataelement(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Dataelement' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Dataelement' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DataelementIntegrationTest.testRemove() {
        Dataelement obj = dod.getRandomDataelement();
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Dataelement' failed to provide an identifier", id);
        obj = Dataelement.findDataelement(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Dataelement' with identifier '" + id + "'", Dataelement.findDataelement(id));
    }
    
}
