// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.co.mdc.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import uk.co.mdc.model.Dataelement;
import uk.co.mdc.model.DataelementDataOnDemand;

privileged aspect DataelementDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataelementDataOnDemand: @Component;
    
    private Random DataelementDataOnDemand.rnd = new SecureRandom();
    
    private List<Dataelement> DataelementDataOnDemand.data;
    
    public Dataelement DataelementDataOnDemand.getNewTransientDataelement(int index) {
        Dataelement obj = new Dataelement();
        setDefinition(obj, index);
        setDescription(obj, index);
        setParentId(obj, index);
        setRefId(obj, index);
        setVdId(obj, index);
        return obj;
    }
    
    public void DataelementDataOnDemand.setDefinition(Dataelement obj, int index) {
        String definition = "definition_" + index;
        obj.setDefinition(definition);
    }
    
    public void DataelementDataOnDemand.setDescription(Dataelement obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void DataelementDataOnDemand.setParentId(Dataelement obj, int index) {
        Integer parentId = new Integer(index);
        obj.setParentId(parentId);
    }
    
    public void DataelementDataOnDemand.setRefId(Dataelement obj, int index) {
        Integer refId = new Integer(index);
        obj.setRefId(refId);
    }
    
    public void DataelementDataOnDemand.setVdId(Dataelement obj, int index) {
        Integer vdId = new Integer(index);
        obj.setVdId(vdId);
    }
    
    public Dataelement DataelementDataOnDemand.getSpecificDataelement(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Dataelement obj = data.get(index);
        Long id = obj.getId();
        return Dataelement.findDataelement(id);
    }
    
    public Dataelement DataelementDataOnDemand.getRandomDataelement() {
        init();
        Dataelement obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Dataelement.findDataelement(id);
    }
    
    public boolean DataelementDataOnDemand.modifyDataelement(Dataelement obj) {
        return false;
    }
    
    public void DataelementDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Dataelement.findDataelementEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Dataelement' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Dataelement>();
        for (int i = 0; i < 10; i++) {
            Dataelement obj = getNewTransientDataelement(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
