// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.co.mdc.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import uk.co.mdc.model.UmlModel;
import uk.co.mdc.model.UmlModelDataOnDemand;

privileged aspect UmlModelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UmlModelDataOnDemand: @Component;
    
    private Random UmlModelDataOnDemand.rnd = new SecureRandom();
    
    private List<UmlModel> UmlModelDataOnDemand.data;
    
    public UmlModel UmlModelDataOnDemand.getNewTransientUmlModel(int index) {
        UmlModel obj = new UmlModel();
        setConceptId(obj, index);
        setDescription(obj, index);
        setRefid(obj, index);
        return obj;
    }
    
    public void UmlModelDataOnDemand.setConceptId(UmlModel obj, int index) {
        Integer conceptId = new Integer(index);
        obj.setConceptId(conceptId);
    }
    
    public void UmlModelDataOnDemand.setDescription(UmlModel obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void UmlModelDataOnDemand.setRefid(UmlModel obj, int index) {
        Integer refid = new Integer(index);
        obj.setRefid(refid);
    }
    
    public UmlModel UmlModelDataOnDemand.getSpecificUmlModel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UmlModel obj = data.get(index);
        Long id = obj.getId();
        return UmlModel.findUmlModel(id);
    }
    
    public UmlModel UmlModelDataOnDemand.getRandomUmlModel() {
        init();
        UmlModel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UmlModel.findUmlModel(id);
    }
    
    public boolean UmlModelDataOnDemand.modifyUmlModel(UmlModel obj) {
        return false;
    }
    
    public void UmlModelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UmlModel.findUmlModelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UmlModel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UmlModel>();
        for (int i = 0; i < 10; i++) {
            UmlModel obj = getNewTransientUmlModel(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
