// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package uk.co.mdc.model;

import org.springframework.beans.factory.annotation.Configurable;
import uk.co.mdc.model.ValuedomainIntegrationTest;

privileged aspect ValuedomainIntegrationTest_Roo_Configurable {
    
    declare @type: ValuedomainIntegrationTest: @Configurable;
    
}
